# Generated by Django 4.0.4 on 2022-06-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0004_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_types', models.CharField(choices=[('x', 'X-Ray'), ('ct', 'CT-Scan'), ('mri', 'MRI')], max_length=100, null=True, verbose_name='Test Type')),
                ('body', models.CharField(choices=[('ab', 'Abdomen'), ('ch', 'Chest'), ('pl', 'Pelvis'), ('ue', 'Upper Extremities'), ('le', 'Lower Extremities'), ('sp', 'Spine'), ('hnf', 'Head, Neck and Face')], max_length=100, null=True, verbose_name='Body Location')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal_doctor', to='register.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_patient', to='register.patient')),
                ('radiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal_radiologist', to='register.radiologist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(null=True, verbose_name='Start Time')),
                ('types', models.CharField(choices=[('consult', 'Consultation'), ('follow', 'Follow-up')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoint_doctor', to='register.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoint_patient', to='register.patient')),
            ],
        ),
    ]
