# Generated by Django 4.0.4 on 2022-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
