# Generated by Django 4.0.4 on 2022-06-04 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_doctor_options_alter_patient_options_and_more'),
        ('core', '0003_alter_referal_body_alter_referal_rad_types_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('x', 'X-Ray'), ('ct', 'CT-Scan'), ('mri', 'MRI'), ('ot', 'Others')], max_length=100, verbose_name='Report Type')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_doctor', to='register.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_patient', to='register.patient')),
                ('radiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_radiologist', to='register.radiologist')),
            ],
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
