# Generated by Django 4.0.4 on 2022-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medreport_radreport_report_analysis_report_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='radreport',
            name='multi_images',
            field=models.FileField(null=True, upload_to='test_file/', verbose_name='Multiple Images'),
        ),
    ]
