# Generated by Django 4.0.4 on 2022-06-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_radreport_multi_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radreport',
            name='multi_images',
        ),
    ]
