# Generated by Django 4.0.4 on 2022-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_doctor_alter_report_radiologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medreport',
            name='Prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='medreport',
            name='med_image',
            field=models.ImageField(blank=True, null=True, upload_to='med_reports/'),
        ),
        migrations.AlterField(
            model_name='medreport',
            name='visit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Visit Reason'),
        ),
        migrations.AlterField(
            model_name='report',
            name='analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Analysis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
