# Generated by Django 4.0.4 on 2022-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_medreport_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radreport',
            name='rad_image',
            field=models.ImageField(blank=True, null=True, upload_to='rad_reports/'),
        ),
        migrations.AlterField(
            model_name='radreport',
            name='test_details',
            field=models.TextField(blank=True, null=True, verbose_name='Test Details'),
        ),
    ]
