# Generated by Django 4.0.4 on 2022-06-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_radreport_rad_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radreport',
            name='body',
            field=models.CharField(choices=[('ab', 'Abdomen'), ('ch', 'Chest'), ('pl', 'Pelvis'), ('ue', 'Upper Extremities'), ('le', 'Lower Extremities'), ('sp', 'Spine'), ('hnf', 'Head, Neck and Face'), ('ot', 'Others')], default='ot', max_length=100, verbose_name='Body Location'),
        ),
        migrations.AddField(
            model_name='radreport',
            name='rad_types',
            field=models.CharField(choices=[('x', 'X-Ray'), ('ct', 'CT-Scan'), ('mri', 'MRI'), ('ot', 'Others')], default='ot', max_length=100, verbose_name='Test Type'),
        ),
    ]
