# Generated by Django 4.0.4 on 2022-06-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_radreport_body_radreport_rad_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radreport',
            name='test_details',
        ),
    ]
