# Generated by Django 4.0.4 on 2022-06-12 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_customuser_first_name'),
        ('core', '0013_remove_radreport_test_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='body',
            field=models.CharField(blank=True, choices=[('ab', 'Abdomen'), ('ch', 'Chest'), ('pl', 'Pelvis'), ('ue', 'Upper Extremities'), ('le', 'Lower Extremities'), ('sp', 'Spine'), ('hnf', 'Head, Neck and Face'), ('ot', 'Others')], default='ot', max_length=100, verbose_name='Body Location'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal_doctor', to='register.doctor'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_patient', to='register.patient'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='rad_types',
            field=models.CharField(blank=True, choices=[('x', 'X-Ray'), ('ct', 'CT-Scan'), ('mri', 'MRI'), ('ot', 'Others')], default='ot', max_length=100, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal_radiologist', to='register.radiologist'),
        ),
    ]
