# Generated by Django 4.0.4 on 2022-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_referal_date_alter_referal_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mcheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rcheck',
            field=models.BooleanField(default=False),
        ),
    ]
