# Generated by Django 4.0.4 on 2022-06-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appointment_mcheck_appointment_rcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='rad_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rad_report', to='core.radreport'),
        ),
    ]
