# Generated by Django 4.0.4 on 2022-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_referal_rad_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
