# Generated by Django 4.0.4 on 2022-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_referal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
