# Generated by Django 4.0.4 on 2022-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiologist',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='info',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pmc',
            field=models.TextField(blank=True, max_length=100, verbose_name='PMC'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=500, verbose_name='Specialization'),
        ),
    ]
