# Generated by Django 4.0.4 on 2022-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_patient_dob_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
