# Generated by Django 4.0.4 on 2022-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pmc',
            field=models.TextField(blank=True, max_length=100, verbose_name='PMC Registeration No'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('gp', 'General Physician'), ('p', 'Pulmonology'), ('r', 'Radiology'), ('o', 'Oncology')], default='gp', max_length=500, verbose_name='Specialization'),
        ),
    ]
