# Generated by Django 4.0.4 on 2022-06-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_customuser_profile_image_alter_doctor_pmc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pmc',
            field=models.CharField(blank=True, max_length=100, verbose_name='PMC Registeration No'),
        ),
    ]
