# Generated by Django 4.0.4 on 2022-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_doctor_pmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pmc',
            field=models.CharField(max_length=100, verbose_name='PMC Registeration No'),
        ),
    ]
