# Generated by Django 4.0.4 on 2022-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstorage',
            name='image',
            field=models.ImageField(null=True, upload_to='temp/'),
        ),
    ]
