# Generated by Django 4.0.4 on 2022-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_tempstorage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstorage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
